services:
  - type: web
    name: charm-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --preload --timeout 120 --workers 3
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10

  - type: static
    name: charm-frontend
    rootDir: diet-recommender-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free
    envVars:
      - key: VITE_BACKEND_URL
        value: https://charm-backend.onrender.com
